# Generated by Django 4.1.7 on 2023-02-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='navbarOptionModel',
            new_name='navbarOption',
        ),
    ]
