# Generated by Django 4.1.7 on 2023-02-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0002_rename_navbaroptionmodel_navbaroption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbaroption',
            old_name='title',
            new_name='name',
        ),
    ]
