# Generated by Django 4.1.7 on 2023-02-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0003_rename_title_navbaroption_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaroption',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
