# Generated by Django 4.1.7 on 2023-02-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0004_alter_navbaroption_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('pragraphOne', models.TextField()),
                ('images', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='postsImages/')),
                ('pragraphTwo', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('NavbarOption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templateHandler.navbaroption')),
            ],
        ),
    ]
