# Generated by Django 4.1.7 on 2023-02-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0009_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pragraphOne',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pragraphTwo',
            field=models.TextField(blank=True),
        ),
    ]
