# Generated by Django 4.1.7 on 2023-02-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0011_rename_navbaroption_post_navbar_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='main_image',
        ),
    ]
