# Generated by Django 4.1.7 on 2023-02-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0013_alter_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='navbar_option_name',
            field=models.ManyToManyField(to='templateHandler.navbaroption'),
        ),
    ]
