# Generated by Django 4.1.7 on 2023-02-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0014_image_navbar_option_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='navbar_option_name',
        ),
    ]
