# Generated by Django 4.1.7 on 2023-02-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0015_remove_image_navbar_option_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='posts',
        ),
    ]
