# Generated by Django 4.1.7 on 2023-02-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0016_rename_post_image_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='posts',
            new_name='post',
        ),
    ]
