# Generated by Django 4.1.7 on 2023-04-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0019_about_homedesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedesign',
            name='created',
        ),
        migrations.RemoveField(
            model_name='homedesign',
            name='updated',
        ),
    ]
