# Generated by Django 4.1.7 on 2023-04-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0020_remove_homedesign_created_remove_homedesign_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedesign',
            name='logoColor',
            field=models.CharField(default='004500', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='homedesign',
            name='webSiteCommit',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='homedesign',
            name='webSiteCommitSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homedesign',
            name='webSiteNameSize',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
