# Generated by Django 4.1.7 on 2023-04-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateHandler', '0022_alter_homedesign_websitenamesize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedesign',
            name='navbaColor',
        ),
        migrations.RemoveField(
            model_name='homedesign',
            name='navbaHoverColor',
        ),
    ]
